### ISSUE TITLE
Взаимодействие тестов друг с другом

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#10]
Для выполнения некоторых тестов мне нужно сначала авторизоваться на сервере. Т.е. сначала нужно выполнить запрос, который вернет куку, а потом все остальные запросы выполнять с этой кукой.

Тут возникает два вопроса:
1. Можно ли задавать порядок тестов, чтобы авторизационный тест выполнится первым?
2. Можно ли данные, полученные в одном тесте, использовать в следующих тестах?

**Comment by melezhik** [comment]
да конечно. для это опять такие же подойдут модули.
- выделяем swat модуль который реализует авторизацию ( аутентефикацию наверное все же? )

```
    echo swat_module=1 > login/swat.ini
    echo 200 OK > login/post.txt
```
- используем его везде, где для валидного запроса нужно сначала залогнитится:

```
   $ cat foo/bar/hook.pm 
   run_swat_module POST => 'login'
```

**Comment by melezhik** [comment]
> Можно ли данные, полученные в одном тесте, использовать в следующих тестах?

речь идет о передачи данных между upstream/downstream историями ? или о передачи данных между двумя произвольными историями?

**Comment by ivanych** [comment]
_Аутентификация, да._

Но этот вариант, я так понимаю - это всё в рамках одного теста. upstream story, да? Получается, если мне нужно проверить 100 методов API, то мне придется 100 раз аутентифицироваться?

**Comment by ivanych** [comment]
Я путаюсь в Вашей терминологии:)

**Comment by melezhik** [comment]
Сейчас все подробно распишу. Как не делать 100 раз вызов метода аутентефикации.

**Comment by melezhik** [comment]
Итак. Допустим успешно  пройденная аутентефикация порождает куку, посылаемую от сервера к клиенту, что бы ее сохранить используем механизм куки джар утилиты curl:

```
$ cat login/swat.ini

swat_module=1 

curl_params="--cookie-jar ${test_root_dir}/cook.txt" # плюс еще возможно нужно добавить параметры для логина , пароля
curl_params="${curl_params} -d login=foo -d password=123456"


$ cat login/post.txt

# успешный логин всегда возвращает это
200 OK

$ cat login/hook.pm

# что бы каждый раз не логинится будучи уже залогининым воспользуемся 
# проверкой наличия файла куки и спуфингом ответа от сервера 
# в данном случае исходим из того,
# что наличие файла с кукой означает успешную аутентификациию
# можно чуть более усложнить проверку
# могу показать потом как 

 if ( -f test_root_dir().'/cook.txt' ) {
   # не посылать запрос к серверу если уже прошли аутентефикацию
    set_response('200 OK');
 }

# в том запросе, где нужна аутентефикация 

$ cat  foo/bar/hook.pm

run_swat_module POST => 'login'

# ну и собственно остается воспользоваться кукой созданной запросом POST login/
$ cat  foo/bar/swat.ini

curl_params="--cookie ${test_root_dir}/cook.txt"

```

**Comment by melezhik** [comment]
поправил опечатку в предыдущем комменте:

${test_root_dir} вместо ${$test_root_dir}

**Comment by melezhik** [comment]
да, конечно, строго говоря swat не позволяет принудительно вызвать ТОЛЬКО ОДИН РАЗ тест в самом начале. Вобще говоря imho это правильно, те тестовые фреймворки , с которыми я сталкивался именно так себя и ведут - тесты расмматриваются как сугубо несвязанные друг с другом юниты, что бы выполнить некие предварительные условия, необходмые для прохождения теста , в обычных юнит тест фреймворках пишут свою функцию ( test::more и т.д ) либо степ (cucumber), в свате в ввиде такой функции выступает сват модуль, т.к. идеология свата для потворно использования кода - swat module (http запрос). Не совсем обычно конечно, но с другой стороны смысл в том, что бы не использовать ничего кроме http запросов (request oriented design) - максимально приблизится к клиент серверной предметной области, что на мой в конце концов делает более простой и ясной процедуру отладки тестов, т.к. вы всегда оперируете именно с http запросами и больше ни с чем , если не хочется по каким-то причинам делать повторно один и тот же запрос - используем спуфинг ( redefine server response )

**Comment by melezhik** [comment]
Для сохранения состояния между upstream story / downstream stories пока можно использоавть обычные глобальные переменные, т.к. upstream story / downstream stories выполняются в одном процессе. В будующем, возможно, придумаю более элегантное решение ( в коде впринципе все для этого есть ). См. абзац -  _"One word about sharing state ... "_ в секции [upstream-and-downstream-stories](https://github.com/melezhik/swat#upstream-and-downstream-stories).

Ну и с другой, стороны никто не мешает написать свой синглтон, и в него записывать любые данные возникающие в контексте выполения swat теста ...

**Comment by ivanych** [comment]
Вот тут не понял:

```
# ну и собственно остается воспользоваться куккой созданной запросом POST login/
$ cat  foo/bar/get.txt

curl_params="--cookie ${$test_root_dir}/cook.txt"
```

Это точно должно быть в foo/bar/get.txt? там же должен быть, "200 OK", установленный из cat login/hook.pm

**Comment by melezhik** [comment]
да опечатался, конечно же имелось ввиду:

```
$ cat  foo/bar/swat.ini

curl_params="--cookie ${$test_root_dir}/cook.txt"
```

**Comment by ivanych** [comment]
Ок, с местом понятно. А зачем оно вообще? Разве этот параметр не будет прочитан из login/swat.ini? Или оно перезапишет?

**Comment by ivanych** [comment]
Или оно будет добавлено к login/swat.ini?

**Comment by melezhik** [comment]
для каждого запроса (swat истории ) используется свой swat.ini файл, лежащий в соответсвующей директории. Если хочется иметь ини файл на весь проект, можно создать swat.ini в корне проекта. Подробнее об этом тут - https://github.com/melezhik/swat#settings-priority-table

**Comment by melezhik** [comment]
т.е. да, логика такая, локальный swat.ini файл переопределяет настройки в проектном swat.ini файле, так же возможно их конкатенация,  в документации есть примеры.

**Comment by melezhik** [comment]
да, но важно понмать, что термин "переопределяет" применним только к жесткому  набору переменых, зарезервированных в swat, в данном случае это переменная curl_params.

**Comment by ivanych** [comment]
А swat.ini модуля и истории как соотносятся? Из таблицы приоритетов непонятно.

**Comment by melezhik** [comment]
```
| location                                  | order N     |
| --------------------------------------------------------|
| ~/swat.ini                                | 1           |
| `project_root_directory'/swat.ini         | 2           |
| `http resource' directory/swat.ini file   | 3           |
| current working directory/swat.my file    | 4           |
| environment variables                     | 5           |
```

Порядковый номер задает приоритет. Т.е. если curl_params будет определен и в project_root_directory'/swat.ini   и в `http resource' directory/swat.ini  , то победит последний.

Если же хочется использовать значение определенное раньше, то можно сделать так:

curl_params="${curl_params} ... "

**Comment by melezhik** [comment]
Сорри, невнимательно прочел вопрос, мой ответ был не про это...

**Comment by melezhik** [comment]
> А swat.ini модуля и истории как соотносятся? Из таблицы приоритетов непонятно.

Никак не соотносятся , т.к. история и swat модуль с точки зрения настроек swat.ini файла - просто разные тесты, причем у каждого могут быть свои swat.ini настройки ( файл $http_resource_dir/swat.ini ) невидимые в других тестах

**Comment by melezhik** [comment]
Михаил, обновил предпоследний свой коммент, что было понятнее

**Comment by ivanych** [comment]
С куками я разобрался, всё отлично работает. 

Передача данных между историями действительно вроде бы не нужна, согласен.

Передачу данных в пределах истории еще не пробовал, завтра попробую. Ну, типа, первый метод тестируемого АПИ вернул некий идентификатор, его надо запомнить и использовать во втором методе.

**Comment by melezhik** [comment]
рад слышать о прогрессе! пишите, если что ...

**Comment by ivanych** [comment]
С авторизацией ясно.

Сохранение состояния между upstream story / downstream stories рассмотрим отдельно в #18
