### ISSUE TITLE
Переменная - откуда был вызван модуль

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#11]
Как в ini-файле модуля определить, из какого хука он был вызван?

Моя структура:

```
/foo
    /virtual
        hook.pm # это хук, отсюда вызывается модуль foo
    swat.ini # это модуль (swat_module=1) и тут нужно знать, откуда вызвали
```

Есть переменная $resource_dir, но в ней находится каталог модуля (foo), а мне нужен каталог хука (foo/virtual).

**Comment by melezhik** [comment]
к сожалению никак. а для чего вам это? приведите конкретный кейс, может быть можно решить как-то подругому?
единственная связь от вызываемого модуля к  вызывающему хуку - это набор переменных модуля, которые можно определить в момент вызова модуля.

```
  run_swat_module ( GET => 'foo/bar' , { foo => 100, bar => 200 } )
```

Но с другой стороны всегда можно "поиграть с глобальными переменными":

```

 # upstream hook.pm
  our $data = { foo => 100, bar => 200 };
  run_swat_module ( GET => 'foo/bar'  )

# модуль hook.pm


 our $data;
 print $data->{foo};
 print $data->{bar};

```

**Comment by ivanych** [comment]
Кейс:

Модуль отправляет на сервер файл.
Файлы разные, каждый хук отправляет свой файл.
В модуле нужно указать curl'у, где лежит отправляемый файл.
А лежит он в каталоге хука.
Соответственно, модулю нужно знать, откуда он был вызван, чтобы обратиться к нужному файлу.

**Comment by ivanych** [comment]
Вроде бы, тут прямо напрашивается создание переменной $hook_dir.

**Comment by melezhik** [comment]
попробуйте так , через переменные модуля, пока поддержки "из-коробки" для hook_dir нет 

upstream - baz
downstream - foo/bar/module

```
# module swat.ini
$ cat foo/bar/module/swat.ini

swat_module=1
# засылаем постом файл foo.txt
# у вас возможно другой способ вызова curl
# но важно, что %path_to_dir% 
# будет заменена на соответсвующую
# переменную модуля
curl_params="-F %path_to_dir%/foo.txt"

# upstream hook.pm
$ cat  baz/hook.pm

run_swat_module( POST => '/foo/bar/module', { path_to_dir => resource_dir()  )

```

**Comment by ivanych** [comment]
Да, я так и сделал, только вместо path_to_dir у меня было hook_dir:)

Но что на счет добавления hook_dir "в коробку"? Мне кажется, это удобно.

**Comment by melezhik** [comment]
идея мне понятна. тут есть проблемы с технической реализацией. дело в том что swat.ini - обычные баш файлы - они исполняются на этапе "компиляции" тестов, т.е. во время генерации тестовых файлов на основе тестовой оснастки swat ( файлы swat проекта ) , на это момент попросту нет информации о том, чему равняется hooks_dir, т.к. это значение устанавливается только в момент выполнения сгенеренных тестов (*.t файлов ).

Как компромисс можно рассмотреть введение макросов или зарезервированных выражений, которые будут вычислятся атоматически  в момент вызова curl комманд, например для нашего случая можно так: 

```
curl_params="-F __UPSTREAM_DIR__/foo.txt"
```

**Comment by ivanych** [comment]
Я думаю, это к интерфейсам модулей можно отнести #9

**Comment by melezhik** [comment]
возможно. нужно будет подумать.

**Comment by ivanych** [comment]
Вопрос в данный момент решен, ссылка в тикете про интерфейсы добавлена, этот тикет закрываю.

**Comment by melezhik** [comment]
да, хорошо.
