### ISSUE TITLE
Игнорировать пустые строки в swat.ini

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#12]
Допустим, есть такой файл swat.ini:

```
curl_params=" \
--data-urlencode 'login=%login%' \
--data-urlencode 'pass=%pass%' \
--data-urlencode 'param1=%param1%' \
--data-urlencode 'param2=%param2%' \
"
```

Хочу отделить параметры login и pass от других параметров пустой строкой, для повышения читабельности:

```
curl_params=" \
--data-urlencode 'login=%login%' \
--data-urlencode 'pass=%pass%' \

--data-urlencode 'param1=%param1%' \
--data-urlencode 'param2=%param2%' \
"
```

Результатом будет ошибка (весьма, кстати, невнятная), потому что строка параметров разорвана, фактически тут две строки и обе неправильные.

Можно исправить это, добавив в пустую строку обратный слеш:

```
curl_params=" \
--data-urlencode 'login=%login%' \
--data-urlencode 'pass=%pass%' \
\
--data-urlencode 'param1=%param1%' \
--data-urlencode 'param1=%param2%' \
"
```

Но этот одинокий слеш мозолит мой глаз перфекциониста:)

Предлагаю сделать так - если строка заканчивается слешем, и за ней идет пустая строка/строки, то игнорировать эти строки.

А возможно, можно поступить еще проще - игнорировать вообще все пустые строки.

**Comment by melezhik** [comment]
Михаил, теперь понял о чем речь. К сожалению данная задача вне скоупа SWAT, т.к. swat.ini файлы обрабатываются как обычные bash скрипты ( SWAT делает простой вызов "source swat.ini" ) - то собственно здесь мы ограничены синткасисом самого bash.

Вприниципе можно как вариант для группировки параметров написать так:

```
# credentials
curl_params=" \
--data-urlencode 'login=%login%' \
--data-urlencode 'pass=%pass%' "

# other params
curl_params=" $curl_params --data-urlencode 'param1=%param1%' \
--data-urlencode 'param2=%param2%'"
```

**Comment by ivanych** [comment]
А шаблоны %% как заменяются на значения?

**Comment by melezhik** [comment]
это происходит уже после выполнения swat.ini файла, в результате этого выполнения в тестовый скрипт экпортируются swat переменные (curl_params, и т.д) _как есть_ и уже внутри тестового скрипта поисходит замена %% на значения переменных модуля. Если нужна еще какая-та поддержка в этом смысле предлагайте. Но суть остается та же.

1) сначала делается source swat.ini файл в резултате которого создаются  переменные окружения
2) переменные окружения записываюся как есть в исходник тестового скрипта, и в момент уже выполнения теста, происходит интерполяция для всех найденных %name%

**Comment by melezhik** [comment]
Михаил, это закрываю?

**Comment by ivanych** [comment]
Если сделать таки ничего нельзя - закрывай:)

**Comment by melezhik** [comment]
боюсь что да, потому как это bash
