### ISSUE TITLE
Не запускается swat

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#14]
Обновился

```
$ git rev-parse HEAD
36310594aa6047c0d2c8f080ac8fd72618f3080c
```

Переустановил.

Запускаю:

```
$ swat -t http_incoming_sms
usage: swat project HOST:port options
```

Каталог с тестом есть, файл host есть, до обновления всё работало:

```
$ test_file=http_incoming_sms swat
....вывод....
```

Это я что-то не понял, или баг?

**Comment by melezhik** [comment]
поправил - aafacd3

**Comment by melezhik** [comment]
был баг :)

**Comment by ivanych** [comment]
Обновился, заработало, спасибо:)

**Comment by melezhik** [comment]
не за что! :)

**Comment by ivanych** [comment]
Либо я снова запутался, либо снова баг:

```
$ swat https://test.local -t cdt
usage: swat project HOST:port options
```

Версия свежая:

```
git rev-parse HEAD
14559951690c5955fb0ec1295a2bf858f10f23e7
```

**Comment by melezhik** [comment]
Михаил, привет!

Согласно документации, первым параметром должен быть корень проекта, т.е. в твоем случае  так:

`swat ./ https://test.local -t cdt`

если же имя хоста прописано в host файле то возможен такой вариант:

`swat  -t cdt`

Swat анализирует переданные ему параметры и все что _не похоже_ на опции (-t, --prove ) обрабатывает так:
- первый параметр, если он указан - это путь к корню проекта иначе, cwd
- второй параметр, если он указан - это имя хоста или base_url, иначе читать его из cwd/host

**Comment by ivanych** [comment]
Тогда документация врет:

```
swat [project_root_dir] [host:port] [swat_command_line_options]
```

Тут сказано, что любой параметр необязателен, независимо от других.

**Comment by ivanych** [comment]
Нужно так:

```
swat [ project_root_dir [host:port] ] [swat_command_line_options]
```

**Comment by melezhik** [comment]
все верно, в твоем случае, ты запускаешь так:

`swat https://test.local -t cdt`
сват воспринимает https://test.local  как корень к проекту и делает проверку на существование данного пути в файловой системе, он не естесвенно не существует , и поэтому возвращается ошибка, возможно нужно еще добавить соответсвующее сообщение, но в целом поведение корректное

Да, согласен, с нотацией 

`swat [ project_root_dir [host:port] ] [swat_command_line_options]`

**Comment by ivanych** [comment]
Поправь и закрывай тикет:)

**Comment by melezhik** [comment]
ага, конечно, как поправлю закрою. С праздниками тебя, Михаил! Судя по твоей активности уже принялся за работу :))))

**Comment by ivanych** [comment]
Спасибо, тебя тоже:)

Да, клиенты устали праздновать, хотят новых прекрасных фич:)

**Comment by melezhik** [comment]
поправил документацию
ушло в  https://github.com/melezhik/swat/releases/tag/0.1.76
