### ISSUE TITLE
Как данные из одного запроса использовать в другом?

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#18]
Мне нужно создать на сервере новую сущность и проверить, что она создалась правильно. Допустим, это регистрация нового пользователя.

Я делаю `POST /user` с данными нового пользователя. Пользователь создается, в ответе прилетает id созданного пользователя. Я проверяю id, он правильный, т.е. сам запрос выполнился успешно. Ок.

Но этого недостаточно. Нужно проверить, что внутри на сервере пользователь создался как надо. Для этого нужно сделать `GET /user/$id` и проверить полученные данные.

Я так пониманию, GET тут должен быть основной историей, а в ней хуком должен быть предварительно вызван POST.

Как прочитать id, полученный в POST? Как его затем использовать в GET?

**Comment by melezhik** [comment]
можно так:

```

$ echo swat_module=1 > user/swat.ini
$ cat  $ user/post.txt
200 OK

$ echo swat_module=1 > user/id/swat.ini
$ cat $ user/id/get.txt
200 OK

# в ответе видимо будет как-то возвращаться user_id ?
generator [ module_variable('user_id') ]

$ cat $ user/id/hook.pm

modify_resource(
 sub { 
    my $r = shift;
    my $user_id = module_variable('user_id');
    s{id}[$user_id] for $r;
    $r;
  }
);

$ cat  user-create/get.txt
OK

$ cat  user-create/hook.pm

run_swat_module( POST => '/user/', { name => 'Михаил', language => 'perl' });
run_swat_module( GET => '/user/id', { user_id => 12345 });

set_response('OK');
```

**Comment by melezhik** [comment]
видимо, ты хотел не совсем этого?  сейчас перепишу по другому немного ...

**Comment by melezhik** [comment]
```

$ echo swat_module=1 > user/swat.ini
$ cat  $ user/post.txt
200 OK
regexp: user created with ID: (\d+)
code:  our $USER_ID = capture()->[0]

$ echo swat_module=1 > user/id/swat.ini
$ cat $ user/id/hook.pm
modify_resource(
 sub { 
    my $r = shift;
    my $user_id = module_variable('user_id');
    s{id}[$user_id] for $r;
    $r;
  }
);
$ cat $ user/id/get.txt
200 OK

$ cat  user-create/get.txt
OK
$ cat  user-create/hook.pm
our $USER_ID;
run_swat_module( POST => '/user/', { name => 'Михаил', language => 'perl' });
run_swat_module( GET => '/user/id', { user_id => $USER_ID });
set_response('OK');
```

**Comment by melezhik** [comment]
в общем и целом данные между различными историями ( в пределах Upstream story / Downstream story ) можно передавать через глобальные переменные. Потом возможно введу что-то вроде универсального хранилища ( stash ), что бы было поэлегантней, но это так "сахар". Но опять так же согласно документации upstream/downstream истории выполняются в одном процессе, поэтом можно использовать обычные глобальные  perl переменные для сохранения состояния. 

Да и для того что бы забирать распарсенные данные из ответа сервера удобно использовать механихм code/captures внтри чеклистов ( как в моем примере ).

**Comment by melezhik** [comment]
Как вариант, если не нравится перемешаить логику запоминания данных с логикой их проверки  в чеклисте , тогда ( вместо указанного способа ) можно воспользоваться фичей response processor : 

добавим запоминание вернувшегося user_id в обработчик ответа ( response processor )

```
$ echo swat_module=1 > user/swat.ini
$ cat  $ user/post.txt
200 OK

regexp: user created with ID: (\d+)

$ cat  $ user/hook.pm

our $USER_ID;

set_response_processor( sub { 

      my $headers   = shift; # original response, http headers, String
      my $body      = shift; # original response, body, String
      $body=~/user created with ID:(\D+)/ and $USER_ID = $1;

      return $headers.$body;     # в данном случае обрабочик ответа нужен только для того, 
                                                # что бы запомнить верунвшееся user_id,
                                                # поэтому ответ не меняем 

});

```

**Comment by melezhik** [comment]
на всякий случай про обработчки ответов сервера написано здесь - https://github.com/melezhik/swat#process-http-responses

**Comment by ivanych** [comment]
Получилось, спасибо. Хотя даже не знаю, каким из предложенных способов - у меня какой-то средний получился:)

Редактор, правда, ругается на использование неинициализированной переменной. Нехорошо, все-таки, глобальные переменные использовать...

**Comment by melezhik** [comment]
> Редактор, правда, ругается на использование неинициализированной переменной. 

Возможно где-то недообявил, поидее такого быть не должно, еще use strict повтыкай на всякий пожарный ....
