### ISSUE TITLE
Ошибка при указании несуществующего каталога

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#19]
Команда

`swat -t несуществующий_каталог`

выдает трассировку перловых вызовов и скрипт падает.

Мне кажется, достаточно одной строчки с сообщением о несуществующем каталоге. Трассировка явно лишняя:)

**Comment by melezhik** [comment]
Михаил, тут к сожалению ничего не сделаешь. Запуском тестов занимается утилита prove, я с ней взаимодействую как с внешним скриптом и никак не могу обрабатывать ее ошибки

**Comment by ivanych** [comment]
Понятно. Жаль.

**Comment by melezhik** [comment]
солгасен, мне тоже этот ужасный трейс от prove не нравится ...
