### ISSUE TITLE
Проверка нескольких вхождений - поиском внутри динамического диапазона 

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#21]
В ответе приходит список значений. Допустим, это числа. Одна строка - одно число:

```
11
22
33
...
```

1) Как проверить, что _каждая_ строка содержит число? Регулярка `^(\d+)$` ищет до первой совпадающей строки (вроде?), а надо все строки проверить.

Ну, или не все, а хотя бы ограниченные неким блоком:

```
строка_начало_блока
11
22
33
...
строка_конец_блока
```

Читал в документации про блоки, но не понял, можно ли так сделать.

2) Как получить список всех захваченных чисел? capture() выдает только первое совпадение, видимо, это из-за того, что в пункте 1) ищется только до первого совпадения.

**Comment by melezhik** [comment]
если строки идут строго одна за одной  и кол-во строк известно, то можно решить через блоки. например:

```
begin:
строка_начало_блока
regexp: (\d+)
code: our @numbers; push @numbers, capture()->[0]
строка_конец_блока
end:
```

**Comment by ivanych** [comment]
Строки одна за другой. Но количество неизвестно.

**Comment by melezhik** [comment]
т.е. кол-во чисел-строк никаким образом заранее узнать нельзя?

**Comment by ivanych** [comment]
И что-то у меня сомнение... Как сват понимает, что регулярка должна примениться к каждой строке, а "строка_начало_блока" - не к каждой? Точно? Не напутал?

**Comment by ivanych** [comment]
Нет, нельзя. Нет такого метода. Допустим, метод выдает список файлов пользователя, но метода, который просто выдаст количество - нет.

**Comment by melezhik** [comment]
swat блоки работают как описано, но у них есть ограничение - ты всегда должен задать (перечислить)  все элементы внутри блока. если ты знаешь кол-во элементов и патерны их описывающие , то тогда блок подойдет для решения этой задачи. поведения как в операторе диапазона `/re1/ ... /re2/` - ( динамические диапазоны ) в Perl нет ( возможно добавлю в будующем, но пока это технически сложновато )

**Comment by melezhik** [comment]
окей, а строки-числа - создержат только числа? есть ли регексп который ОДНОЗНАЧНО определяет, что данная строка - число-строка-нужная-тебе ... ?

**Comment by ivanych** [comment]
Погоди, ты хочешь сказать, что в блоке нужно будет написать 

```
regexp: (\d+)
regexp: (\d+)
regexp: (\d+)
и так много раз?
```

Ну ладно, фиг бы с ним, даже если список из тысячи строк. Но количество неизвестною, вот в чем беда. Диапазон был бы кстати, да.

> окей, а строки-числа - создержат только числа? есть ли регексп который ОДНОЗНАЧНО определяет, что данная строка - число-строка-нужная-тебе ...

Ну да, регулярку я составлю, от начала и до конца строки, это-то просто.

**Comment by ivanych** [comment]
Точнее не диапазон, а, скорее, итератор.

```
(\d+) x 10
```

типа того.

**Comment by melezhik** [comment]
> Ну ладно, фиг бы с ним, даже если список из тысячи строк.
> руками не обязательно все 1000 строк вписывать, можно было бы использовать фичу `generator:` .

**Comment by melezhik** [comment]
> (\d+) x 10

извини, а что такое 10, что это за константа?

**Comment by ivanych** [comment]
10 - это я плохой пример привел. Там должна быть звездочка.

**Comment by ivanych** [comment]
А может переформулировать это по другому? Я могу составить регулярку, которая накроет весь ответ, но тогда нужно иметь возможность отключать построчную проверку ответа. Чтобы весь ответ проверялся как одна строка.

**Comment by ivanych** [comment]
Хотя лучше бы конечно итератор в блоке

```
begin:
строка_начало_блока
regexp: (\d+) x *
code: our @numbers; push @numbers, capture()->[0]
строка_конец_блока
end:
```

**Comment by melezhik** [comment]
> (\d+) x *

Михаил, извини, не понял, а это констркукция что означает?

**Comment by ivanych** [comment]
Ну, как звездочка в регулярке. Повторить для произвольного количества строк.

**Comment by melezhik** [comment]
понятно, это и есть оператор диапозона `a ... b` в Perl,  если бы swat блоки работали в таком режиме можно было бы ... но сейчас увы так нельзя. 

тот вариант, который я предлагал в качестве альтернативы это использовать response processors для вычисления длины списка, затем герератор для герерации swat блока, но получается очень конечно громоздко:

```
our $list = [ 'begin:' , 'строка_начало_блока' ];
set_response_processor( sub { 
      my $headers   = shift; # original response, http headers, String
      my $body      = shift; # original response, body, String
      for my $l ( split $body, "\n" ) {
        push @$list,   qq/regexp: \d+/; 
        push @$list,   qq/code: our @numbers; push @numbers, capture()->[0]/; 
      }
      push @$list,   qq/'end:'/; 
      push @$list,   qq/'строка_конец_блока'/; 
      return $headers.$body;  
    });

# cat get.txt
generator: our $list;
```

**Comment by ivanych** [comment]
Не, диапазон - это `a .. z`, генерирует  `аbcdefg...`. 

А я имею в виду итератор - `a x n`, генерирует `aaaaaa...`. Только вместо n нужна звездочка.

**Comment by ivanych** [comment]
response processors  - мне его нужно вызывать внутри модуля, это еще неудобнее. Нужно как-то передавать в модуль параметр, который будет включать/выключать этот обработчик, потому что в других вызовах этого модуля этот обработчик не требуется.

**Comment by melezhik** [comment]
в Perl есть два вида оператора диапазона ( один - тот о котором ты говоришь -  Binary "x" repetition operator.  ), а есть другой, который делает как раз то, что тебе нужно - http://perldoc.perl.org/perlop.html#Range-Operators

**Comment by ivanych** [comment]
Ты что-то путаешь... Второй оператор `..` - это переключатьль flip-flop.

**Comment by melezhik** [comment]
ну да и его я и мел ввиду, он называется по их документации - Range Operator ( Binary ".." is the range operator  ) - http://perldoc.perl.org/perlop.html#Range-Operators

**Comment by ivanych** [comment]
Ну ладно, не важно.

В общем, мысль такая - хорошо бы научить блоки находить произвольное количество совпадений.

**Comment by melezhik** [comment]
если бы swat блоки могли работать в таком режиме то можно было бы написать так:

```
begin(строка_начало_блока)
regexp /d+
end(строка_конец_блока)
```

т.е. искать все, что между строка_начало_блока и строка_конец_блока

на perl это было бы так:

```
if ( /строка_начало_блока/ ... /строка_конец_блока/){
  /\d/
}
```

**Comment by ivanych** [comment]
А, ну да, если строка_начало_блока и трока_конец_блока работали бы как включатель и выключатель, было бы отлично.

**Comment by melezhik** [comment]
да, я это имеел ввиду, imho это более логичное развитие swat блоков! :smile:

**Comment by ivanych** [comment]
Ну хорошо, а как мне сейчас быть?

Из теста вызывается сват-модуль, в котором вызывается  метод API, возвращающий список чисел. Мне не хотелось бы в модуле делать response processors, потому что этот модуль вызывают и другие тесты, которым не надо считать, сколько там чисел вернулось. 

Можно ли сделать  response processors так, чтобы он вызывался только в одном тесте?

**Comment by ivanych** [comment]
Во, идея - если бы  run_swat_module возвращал ответ сервера, то я бы этот ответ сам обработал и посчитал.

**Comment by ivanych** [comment]
А хотя погоди... зачем мне тогда вообще сват...

**Comment by ivanych** [comment]
Блин, я запутался:)

**Comment by melezhik** [comment]
Михаил, чуть позже отпишу, сейчас по работе немного запарка , извини

**Comment by ivanych** [comment]
Это я должен извиняться, мозг тебе выношу:)

Спасибо, за помощь, реально.

**Comment by melezhik** [comment]
> Можно ли сделать response processors так, чтобы он вызывался только в одном тесте?

да. просто добавь переменную модуля, что-то типа count_numbers ну или как нравится:

```
if ( module_variable('count_numbers')){
 set_response_processor( sub {  # ....
 })
}
```

**Comment by melezhik** [comment]
Михаил, я думаю что в ближайшее время внедрю фичу с поиском внутри динамического диапазона ( с  выключателями ), так что если можешь - подожди, с ней все будет гораздо проще

**Comment by ivanych** [comment]
Отлично! 

Подождать не проблема, еще мильен других методов не покрыты тестами:)

**Comment by melezhik** [comment]
Прототип фичи реализовал, можо попробовать.
- поставь Outthentic::DSL из гита - https://github.com/melezhik/outthentic-dsl
- напиши так:

```

# переходим в режим поиска в диапазоне
# строка_начало_блока строка_начало_блока - должны быть регекспами

between: строка_начало_блока строка_начало_блока
regexp: (\d+)
code: our @numbers; push @numbers, capture()->[0]

# если нужно вернуться в обычный режим (перестать искать в диапазоне, и начать снова искать по всему ) - то вызываем reset_context:

reset_context:
foo
bar


```

**Comment by melezhik** [comment]
про between выражения можно почитать поподробнее здесь - https://github.com/melezhik/outthentic-dsl#between-expressions

**Comment by ivanych** [comment]
Правильно ли я понял:
- для каждой строки ответа
- находящейся между строка_начало и строка_конец
- будет выполнено всё, что написано между between и reset_context

?

**Comment by melezhik** [comment]
да

**Comment by melezhik** [comment]
но можно но и не добавлять reset_context, он нужен если ты хочешь вернуться в нормальный режим (из режима поиска внутри диапазона ) - т.е. снова искать по всему

**Comment by ivanych** [comment]
Ок. Я прошу прощения,  сейчас занят, не могу протестить. Как особожусь, проверю, сразу отпишусь.

**Comment by melezhik** [comment]
т.е. возможны и такие вариации:

```
between foo bar
# ищем в диапазоне между /foo/ ... /bar/

between fooo baaaar
# ищем в диапазоне между /fooo/ ... /baaaar/

reset_context:

# снова ищем везде 

```

**Comment by melezhik** [comment]
> Ок. Я прошу прощения, сейчас занят, не могу протестить. Как особожусь, проверю, сразу отпишусь.

Не вопрос, конечно ...

**Comment by melezhik** [comment]
Михаил, когда будешь ставить outthentic-dsl - то стать с последних коммитов, я там кое-что еще подрихтовал

**Comment by melezhik** [comment]
зачистка старого
