### ISSUE TITLE
Юникод

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#22]
Некоторые параметры в post-запросе содержат юникод (кириллица). В файле hook.pm, где эти параметры задаются, указано use utf8.

В результате, при запуске выдается предупреждение:

```
Wide character in print at /usr/local/share/perl/5.18.2/Test/Builder.pm line 1826
```

Некрасиво как-то...

**Comment by melezhik** [comment]
А можно полностью привести test suite, что бы вопроизвести?

**Comment by ivanych** [comment]
Ха. Попробовал сейчас сделать минимальный проблемный код, и выяснил, что этот варнинг выдает функция diag.

**Comment by melezhik** [comment]
Боюсь тогда с этим вряд ли что сделаешь ...

**Comment by ivanych** [comment]
Мда. Ну ладно.
