### ISSUE TITLE
Обрезаются названия тестов при выводе на экран

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#24]
В файле get.txt написана строка, которую надо найти в ответе сервера:
```
Я прекрасная замечательная строка
```

При запуске выводится следующее:
```
ok 2 - text has ' Я прекрасная замечател'
```

Т.е. строка найдена, всё отлично. Но строка при выводе обрезана. Из-за этого не очень понятно, какая именно строка найдена.

С одной стороны я понимаю, что искомая строка может быть длиннющей, но с другой стороны, если я знаю, что строка не особо длиннющая, то я хочу её видеть полностью.

Нельзя ли это как-то регулировать? Опция какая-нибудь?

**Comment by melezhik** [comment]
Два варианта:

```
$ cat swat.ini
match_l=1000 # обрезать заматченные строки до 1000 байт
```

или


`match_l=1000 swat ...`

См описание `match_l` в https://github.com/melezhik/swat#swat-variables

**Comment by ivanych** [comment]
Ага, работает, спасибо. Я почему-то думал, что это prove делает, его опции смотрел.
