### ISSUE TITLE
Лишние(?) сведения в выводе

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#25]
Наблюдение. Даже не знаю, баг это или что.

В общем, если тест проваливается, то выводится примерно следующее:

```
not ok 2 - text has '200 OKqqqqqq'
#   Failed test 'text has '200 OKqqqqqq''
#   at /usr/local/share/perl/5.22.1/swat.pm line 252.
```
В модульных тестах комментарий с номером ошибочной строки имеет смысл. Но в swat получается вроде бы бессмысленно - зачем мне знать номер строки в swat.pm?

**Comment by melezhik** [comment]
дело в том, что swat использует `prove//TAP` так что формат вывода наследуется оттдуа. Кстати в Outthentic по-другому, дам другой, на мой взляд более логичный формта без трейса

**Comment by ivanych** [comment]
Outthentic же потребует написать руками код для загрузки страниц, а в swat-е это уже cделано:)

А нельзя в swat-е сделать так же, как в Outthentic-е, если уж ты говоришь, что там лучше сделано?

**Comment by melezhik** [comment]
Привет.
Swat и Outthentic на данный момент сильно отличаются, что бы портировать фичи из Outthentic в swat.

**Comment by melezhik** [comment]
Закрываю. В последней версии вывода TAP нет, формат отчетов совершенно другой.
