### ISSUE TITLE
Опции prove - улучшение документации 

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#27]
Делаю
```
swat --prove '--nocolor'
```
с целью убрать раскрашивание вывода.

Вывод внезапно схлопывается до пары строчек типа
```
/home/ivanych/.swat/.cache/25957/prove/_tc/areas/simple/META/request.t .......... ok   
```
в то время, как без --prove выводится всё подробно, по каждому тесту.

Чего это оно? Я же только про цвета опцию использовал, ничего другого менять не надо...

И кстати, про цвета. Оказалось, что цвета этой опцией не убираются. А как убрать цвета? В документации самого swat-a нашел только swat_disable_color, но там сказано, что оно и так по умолчанию выключено.

**Comment by ivanych** [comment]
А! пардон, выключено swat_disable_color - это же двойное отрицание:) Включил, заработало:)

**Comment by melezhik** [comment]
вот так правильно:

`swat_disable_color=1 swat --prove '--nocolor -v'`
 *  `swat_disable_color` - выключает swat вывода
 * `--prove` - задает опции для prove в данном случае - вербозный вывод и без цвета

**Comment by ivanych** [comment]
```
swat_disable_color=1 swat --prove '--nocolor -v'
```
Да, но речь-то о том, что я указал только опцию про цвета, а оно вдруг стало не вербозное.

**Comment by melezhik** [comment]
По-дефолту, когда не указываются опции для prove явно,  swat запускает prove с параметрами "-v" , что обеспечивает детализацию вывода от prove, если пользователь переопределяет параметры для prove , то используются пользовательские параметры, в данном случае запуск prove с параметрам "--nocolor" не даёт детализации, так как по умолчанию в prove она выключена

**Comment by ivanych** [comment]
Ага, понятно. Может быть, указать в документации? Ну, что по умолчанию -v, а если указать -prove, то всё сбрасывается и надо самому всё указывать?

**Comment by melezhik** [comment]
Да , согласен. Переоткрываю тикет для улучшения документации.

**Comment by ivanych** [comment]
А кстати, оно там даже указано, но не там, где следовало бы:)

**Comment by melezhik** [comment]
Закрываю. В последней версии prove уже нет.
