### ISSUE TITLE
Swagger compliance

### ISSUE THREAD

**Issue by sergeyromanov** [melezhik/swat#3]
I think it would be very nice to have a way of generating swat test harness based on a [Swagger spec file](http://swagger.io/specification/).

What do you think?

**Comment by melezhik** [comment]
Hi Sergey! I have never had an experience with swagger ...  But it looks like people use it alot , so it'd good. A kind of scaffolding I recently did for mojolicious framework - https://github.com/melezhik/Mojolicious-Command-Swat ... BTW, do you want to contribute in swagger/swat integration ?

**Comment by sergeyromanov** [comment]
I am introducing a Swagger-based doc for an API at my $job at the moment. If I'll have some tuits, I will try play with swat as a test framework. Can't promise anything, but hopefully I'll try to come up with some prototype ;)

**Comment by melezhik** [comment]
@sergeyromanov  это еще актуально?

**Comment by sergeyromanov** [comment]
Лично мне -- нет, в том проекте я уже не участвую.
(fun fact: в предыдущем комментарии `$job == 'EPAM'`)

**Comment by melezhik** [comment]
Хорошо, закрываю тогда тикет.
