### ISSUE TITLE
Сделать возможность обработки ответов с любым http-кодом

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#5]
Если сервис отвечает с кодом, отличным от 200, тело ответа игнорируется.

Нужно сделать возможность обрабатывать тело ответа с любым кодом.

**Comment by melezhik** [comment]
Есть вариант заюзать curl -w "{http_code}" для проверки http статуса, что избавит от необходимости запускать curl с флагом -f ... Завтра посмотрю ...

**Comment by melezhik** [comment]
пофиксил, поставьте из гита. для того что бы получать тело ответа в случае неуспешного http статуса нужно выставить ignore_http_err=1 лучше всего в swat ини файле ресурса ( а не всего проекта )

например для ресурса foo:

```
cat foo/swat.ini 
ignore_http_err=1

```

подробнее про ignore_http_err  тут - https://github.com/melezhik/swat#swat-variables

**Comment by ivanych** [comment]
А для чего вообще эта опция? Почему бы всегда не запускать без -f?

**Comment by melezhik** [comment]
на самом деле считаю что запускать с -f наоборот нужно - это дает автоматическую валидацию в случае неуспешного http ответа, т.е.  тому кто пишет сват тесты даже не нужно писать

`echo  200 OK > get.txt`

в этом случае, достаточно создать пустой get.txt

`touch get.txt`

сват сам провалидирует ситуацию когда будет неуспешный http ответ

Но если хочется изменить такое поведение, то ипользуем ignore_http_err=1

**Comment by ivanych** [comment]
Оке, теперь работает.
