### ISSUE TITLE
Модификаторы регулярных выражений

### ISSUE THREAD

**Issue by ivanych** [melezhik/swat#8]
Как в регулярном выражении указать начало и конец строки в многострочном тексте?

К примеру, в тексте

```
test1
no test2
test2
test3
```

мне нужно проверить наличие строки

```
^test2$
```

Если просто написать

```
regexp: test2
```

то будет совпадение со второй строкой (no test2), а это неправильно.

Если же написать

```
regexp: ^test2$
```

то совпадений вообще не будет, что тоже неправильно.

Тут нужен модификатор /m, но как его указать в свате?

**Comment by ivanych** [comment]
А, стоп, поторопился...

**Comment by ivanych** [comment]
сват проверяет не весь ответ сразу, а построчно?

**Comment by melezhik** [comment]
да, сват работает в однострочном ( построчном ) режиме, если хочется многострочности могут помочь блоки , но не всегда - https://github.com/melezhik/outthentic-dsl#comments-blank-lines-and-text-blocks ибо они не являются полноценной заменой многострочных регэкспов.

Сразу скажу, что специально решил не возится с многострочностью, ибо не уверен что в этом есть большая польза ...

**Comment by melezhik** [comment]
распишите какой у вас кейс, можно попробать заюзать блоки

**Comment by ivanych** [comment]
Да, через секунда после отправки этого тикета я всё понял, и про блоки тоже:) Вопрос снят:)

**Comment by melezhik** [comment]
отлично!
